version: "3.5"
services:
  redis:
    image: redis:latest
    container_name: ev_webservice_redis
    ports:
      - "6379:6379"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - web-service
  mongo:
    image: mongo
    container_name: ev_webservice_mongodb
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - web-service
  app:
    container_name: ev_webservice
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    environment: # Pass environment variables to the service
      REDIS_URL: redis:6379
      MONGO_URL: mongodb://mongo:27017/
      VIRTUAL_HOST: 20.37.48.255
      LETSENCRYPT_HOST: 20.37.48.255
    depends_on:
      # We now depends on node and mongodb server
      - "mongo"
      - "redis"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - web-service

volumes:
  mongodata:

# Networks to be created to facilitate communication between containers
networks:
  web-service:
