version: 1.0.0
debug: true
server:
  port: 8080
database:
  driver: "mongodb"
  host: "0.0.0.0"
  port: 27017
  name: "ev_webservice"
db_source: "mongodb://0.0.0.0:27017/"
token_secret_key: 12345678901234567890123456789012
# token_duration: 15m
file_storage_path: "./storage"
newrelic_key: "4d21aadefd75ec59bef219dbe9c1b63710d0NRAL"
assets_url: "http://localhost:8080/assets"
rpc_server_url: "http://localhost:8088/json-rpc"
