version: 1.0.0
debug: true
server:
  port: 8080
database:
  driver: "mongodb"
  host: "localhost"
  port: 27017
  name: "ev_webservice"
db_source: "mongodb://mongo:27017/"
token_secret_key: "12345678901234567890123456789012"
token_duration: "15m"
